package com.evgeny.goncharov.catapp.consts

const val TAG_APPLICATION_CONTEXT = "TAG_APPLICATION_CONTEXT"
const val TAG_ACTIVITY_CONTEXT = "TAG_ACTIVITY_CONTEXT"

const val TAG_LIFECYCLE_WALL_CAT = "TAG_LIFECYCLE_WALL_CAT"
const val TAG_LIFECYCLE_CAT_DESC = "TAG_LIFECYCLE_CAT_DESC"