package com.evgeny.goncharov.catapp.consts

const val TAG_APPLICATION_CONTEXT = "TAG_APPLICATION_CONTEXT"
const val TAG_ACTIVITY_CONTEXT = "TAG_ACTIVITY_CONTEXT"

const val TAG_MAIN_SCOPE_GET_FROM_APP = "TAG_MAIN_SCOPE_GET_FROM_APP"
const val TAG_IO_SCOPE_GET_FROM_APP = "TAG_IO_SCOPE_GET_FROM_APP"